language: python

python:
  - "3.9"

matrix:
  fast_finish: true

before_install:
  - cd flicker_detection/flicker_detection/tests/

install:
  - pip install -r ../requirements.txt

before_script:
  - wget https://www.techsol.cc/data/googlecv/facenet_model.lite.h5 -O ../preprocessing/embedding/models/facenet_model.lite.h5

script:
  - pytest
