# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - NTU-Google-Testing-Backend1(Production), Build and deploy Python app

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: NTU-Google-Testing-Backend1 # set this to your application's name
  WORKING_DIRECTORY: "flicker_detection/flicker_detection" # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: "3.8"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # checkout the repo
      - name: "Checkout Github Action"
        uses: actions/checkout@master

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build using AppService-Build
        uses: azure/appservice-build@v2
        with:
          platform: python
          platform-version: ${{ env.PYTHON_VERSION }}
          source-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run Azure webapp deploy action using publish profile credentials
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3B3065F7BBB54D7DA1FE95F738872FD6 }}
          package: ${{ env.WORKING_DIRECTORY }}
